name: Build Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
        include:
        # - goos: windows
        #   ext: '.dll'
        - goos: darwin
          ext: '.dylib'
        - goos: linux
          ext: '.so'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup osxcross (for darwin builds only)
      if: matrix.goos == 'darwin'
      run: |
        sudo apt-get install -y clang
        git clone https://github.com/tpoechtrager/osxcross.git
        wget -P osxcross/tarballs https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.15.sdk.tar.xz
        UNATTENDED=yes OSX_VERSION_MIN=10.6 osxcross/build.sh
      shell: bash

    - name: Build Library
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        export CC=${{ matrix.CC }}
        export CGO_ENABLED=1
        export PATH="$(pwd)/osxcross/target/bin:$PATH"
        cd go
        go mod tidy
        go build -o sapphirewrapper${{ matrix.ext }} -buildmode=c-shared
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sapphirewrapper-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./sapphirewrapper${{ matrix.ext }}

